version: "3.8"
services:
    php:
        # PHP Service configuration
        container_name: api-app
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8803:8803
        depends_on:
            - api-db
        networks:
            - api-net

    api-db:
        # MySQL Database Service configuration
        container_name: api-db
        image: mysql:8.0
        ports:
            - 3313:3313
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - TZ=Asia/Shanghai
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - api-net

    phpmyadmin:
        # PHPmyAdmin Service configuration
        image: phpmyadmin:5.2.0-apache
        container_name: api-phpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - 8103:80
        networks:
            - api-net
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=10000M

networks:
    api-net:
        driver: bridge

volumes:
    db-data: ~
